# config.py

DATA_PATH = "reviews_master.csv"
PLATFORMS = ["Myntra", "AJIO", "Amazon India", "Flipkart"]
CATEGORIES = [
    "Women's Ethnic", "Men's Casual", "Kidswear", "Footwear", "Accessories"
]


# New: define a product catalog
PRODUCTS = [
    "T-Shirt", "Jeans", "Sneakers", "Handbag", "Sunglasses",
    "Dress", "Jacket", "Watch", "Wallet", "Hat"
]

SAMPLE_REVIEWS = [
    "Loved the fabric quality, will buy again!",
    "Size runs small, had to return.",
    "Delivery was late and packaging was damaged.",
    "Very comfortable and true to size.",
    "Colors fade after one wash.",
    "Excellent customer service experience.",
    "Material feels cheap, not worth the price.",
    "Stylish design, got compliments.",
    "Stitching came off after a week.",
    "Battery backup is amazing, highly recommend.",
    "Fit was perfect, really impressed!",
    "Too tight around the shoulders.",
    "Delivery was super fast and hassle-free.",
    "Fabric tore within two wears.",
    "Great value for money!",
    "Packaging was neat and elegant.",
    "Terrible stitching, fell apart quickly.",
    "Color was completely different from the picture.",
    "Item is overpriced for the quality.",
    "Nice pattern, looks good with jeans.",
    "Came earlier than expected, good service.",
    "Wrong size sent, very disappointed.",
    "Material feels premium and soft.",
    "Low-quality zip broke in a day.",
    "Awesome color and trendy design.",
    "Size chart was misleading.",
    "Threads coming out of seams.",
    "Eco-friendly packaging, well done!",
    "Washed it once and it shrank.",
    "Excellent fabric, breathable and light.",
    "Received used item, very unhappy.",
    "Refund was processed quickly.",
    "Looks great but not comfortable.",
    "Order was cancelled without notice.",
    "Fit is weird around the waist.",
    "Delivery guy was rude.",
    "Nice texture, feels smooth on skin.",
    "Prints started fading instantly.",
    "True to color, exactly as shown.",
    "Came with missing buttons.",
    "Value for price is questionable.",
    "Pattern is modern and attractive.",
    "Slightly large but wearable.",
    "Good for casual wear.",
    "Zip doesn't work properly.",
    "Lightweight and easy to carry.",
    "Box was torn on arrival.",
    "Comfortable and stylish!",
    "Too expensive for what it offers.",
    "Customer service didn’t respond.",
    "Love the design and fabric combo.",
    "Looks classy, feels average.",
    "Arrived two days late.",
    "Soft fabric, but stitching needs improvement.",
    "Delivery fast, but box was open.",
    "Product arrived wet and dirty.",
    "Material has a weird smell.",
    "Top-notch quality, highly recommended.",
    "Wrong item sent.",
    "Material catches lint easily.",
    "Fit is elegant and modern.",
    "Feels rough on skin.",
    "Durability is questionable after a week.",
    "Matches product description perfectly.",
    "Tight around the arms.",
    "Great for the price!",
    "Threads came out after one wear.",
    "Color is vibrant and beautiful.",
    "Loose threads everywhere.",
    "Packaging was fancy but product was broken.",
    "Elegant fit, compliments every time.",
    "Quality better than expected.",
    "Strange chemical odor on arrival.",
    "Creased heavily after unpacking.",
    "Good stitching overall.",
    "Material feels nice, not itchy.",
    "Horrible experience with delivery.",
    "Easy returns process.",
    "Impressive design innovation.",
    "Came in wrong color.",
    "Really fast delivery, thanks!",
    "Not worth the money.",
    "Amazing fit and comfortable all day.",
    "Completely different from image.",
    "Damaged piece sent twice.",
    "Too baggy and loose.",
    "Great texture and build.",
    "Difficult to wear, poor design.",
    "Comfortable material but terrible zip.",
    "Absolutely love the packaging!",
    "Looks better than expected.",
    "Cheap finish on sleeves.",
    "Size is too inconsistent.",
    "Trendy color and awesome comfort.",
    "Got stains on the product.",
    "Fast shipping, will buy again.",
    "Uncomfortable and stiff fabric.",
    "Perfect summer outfit.",
    "Shiny finish looks cheap.",
    "Good customer support!",
    "Excellent stitching and perfect size."
]
